---
# tasks file for atlassian-confluence

- name: install requirements
  apt: name={{ item }} state=present
  with_items:
    - python-lxml
  tags:
    - atlassian-confluence
 
- name: set basic facts
  set_fact:
    download_url: "{{ atlassian_confluence_baseurl }}/atlassian-confluence-{{ atlassian_confluence_version }}.tar.gz"
    download_tmp: "{{ atlassian_confluence_basedir }}/atlassian-confluence-{{ atlassian_confluence_version }}.tar.gz"
    atlassian_confluence_dir: "{{ atlassian_confluence_basedir }}/atlassian-confluence-{{ atlassian_confluence_version }}"
  tags:
    - atlassian-confluence

- name: create application group
  group: name={{ atlassian_confluence_group }} system=no gid={{ atlassian_confluence_gid }} state=present 
  tags:
    - atlassian-confluence

- name: create user
  user: name="{{ atlassian_confluence_user }}" system=no createhome=no comment="Atlassian Confluence" group={{ atlassian_confluence_group }} home=/nonexistant shell=/bin/false state=present
  tags:
    - atlassian-confluence

- name: create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ atlassian_confluence_basedir }}",
        owner: 'root',
        group: 'root',
        mode: '0751' }
    - { path: "{{ atlassian_confluence_home }}",
        owner: "{{ atlassian_confluence_user }}",
        group: "{{ atlassian_confluence_group }}",
        mode: '0750' }
  tags:
    - atlassian-confluence

- name: download atlassian-confluence tar.gz
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_tmp }}"
    validate_certs: no
    force: no
  tags:
    - atlassian-confluence

- name: extract the atlassian-confluence tar.gz
  unarchive:
    copy: no
    creates: "{{ atlassian_confluence_dir }}"
    owner: root
    group: root
    src: "{{ download_tmp }}"
    dest: "{{ atlassian_confluence_basedir }}"
  tags:
    - atlassian-confluence

- name: fix directory permissions
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - { path: "{{ atlassian_confluence_dir }}/temp",
        owner: "{{ atlassian_confluence_user }}",
        group: "{{ atlassian_confluence_group }}" }
    - { path: "{{ atlassian_confluence_dir }}/work",
        owner: "{{ atlassian_confluence_user }}",
        group: "{{ atlassian_confluence_group }}" }
    - { path: "{{ atlassian_confluence_dir }}/logs",
        owner: "{{ atlassian_confluence_user }}",
        group: "{{ atlassian_confluence_group }}" }
  tags:
    - atlassian-confluence

- name: set confluence.home variable
  lineinfile:
    dest: "{{ atlassian_confluence_dir }}/confluence/WEB-INF/classes/confluence-init.properties"
    regexp: "^confluence.home=}"
    insertafter: "^# confluence.home=/var/data/confluence/"
    line: "confluence.home={{ atlassian_confluence_home }}"
    state: present 
  tags:
    - atlassian-confluence

- name: change server.xml
  xml:
    file: "{{ atlassian_confluence_dir }}/conf/server.xml"
    xpath: "{{ item.xpath }}"
    ensure: "{{ item.ensure|default('present') }}"
    attribute: "{{ item.attribute|default('') }}"
    value: "{{ item.value|default('') }}"
  with_items: atlassian_confluence_server_xml
  tags:
    - atlassian-confluence

- name: catalina enviroment settings (1)
  lineinfile:
    dest: "{{ atlassian_confluence_dir }}/bin/setenv.sh"
    regexp: '^CATALINA_OPTS_ANSIBLE='
    line: 'CATALINA_OPTS_ANSIBLE="{{ atlassian_confluence_catalina_opts|join(" ")}}"'
    insertbefore: '^CATALINA_OPTS'
  tags:
    - atlassian-confluence

- name: catalina enviroment settings (2)
  lineinfile:
    dest: "{{ atlassian_confluence_dir }}/bin/setenv.sh"
    regexp: '^CATALINA_OPTS="\$\{CATALINA_OPTS_ANSIBLE\} '
    line: 'CATALINA_OPTS="${CATALINA_OPTS_ANSIBLE} ${CATALINA_OPTS}"'
    insertbefore: '^export CATALINA_OPTS'
  tags:
    - atlassian-confluence

- name: create template startup sctipts
  template:
    src: "{{ item }}"
    dest: "{{ atlassian_confluence_dir }}/{{ item }}"
  with_items:
    - startup-init.d
    - startup-supervisord
  tags:
    - atlassian-confluence
